@TmsApi_HostAddress = http://localhost:5187

GET {{TmsApi_HostAddress}}/api/assessments/results
X-Training-User: Adnan
Accept: application/json


###
POST  {{TmsApi_HostAddress}}/api/enrollments/test?studentId=S-001&courseCode=CS-101
X-Training-User: Adnan
Accept: application/json