@TmsApi_HostAddress = http://localhost:5187

GET {{TmsApi_HostAddress}}/api/assessments/results
X-Training-User: Adnan
Accept: application/json


###
POST  {{TmsApi_HostAddress}}/api/enrollments/test?studentId=S-001&courseCode=CS-101
X-Training-User: Adnan
Accept: application/json


###
POST  {{TmsApi_HostAddress}}/api/enrollments
X-Training-User: Adnan
Accept: application/json
Content-Type: application/json

{
    "studentId": "S-001",
    "courseCode": "CS-101"
}

###
DELETE {{TmsApi_HostAddress}}/api/enrollments/{Id}
X-Training-User: Adnan
Accept: application/json

###
GET {{TmsApi_HostAddress}}/api/error
X-Training-User: Adnan
Accept: application/json

###
GET  {{TmsApi_HostAddress}}/api/enrollments/{Id}
X-Training-User: Adnan
Accept: application/json

###
GET http://localhost:5187/api/v1/courses

###
GET http://localhost:5187/api/v2/courses

//to test a Valid Enrollment
###
POST http://localhost:5187/api/v2/enrollments
Content-Type: application/json

{
    "studentId": 1,
    "courseCode": "CSE-101"
}

//to test Invalid Course Code
###
POST http://localhost:5187/api/v2/enrollments
Content-Type: application/json

{
  "studentId": 1,
  "courseCode": "invalid"
}

//to test Course does not exist
###
POST http://localhost:5187/api/v2/enrollments
Content-Type: application/json

{
  "studentId": 1,
  "courseCode": "ZZZ-999"
}

//to test same StudId and Course to get 409 (Duplicate Enrollment)
###
POST http://localhost:5187/api/v2/enrollments
Content-Type: application/json

{
  "studentId": 1,
  "courseCode": "CSE-101"
}